### PR TITLE
Remove screenshot bar

### LINKED ISSUE #119: Remove text "Screenshots" from screenshot section
Everybody can see the screenshots are screenshots. I think the text and drop down arrow should be removed.

### PR DESCRIPTION
**Pull request by magnus-ISU**
~~This is not quite yet ready to merge.~~ It is now.

As noted in the discussion, a preference has been added to not load screenshots - useful for low-network situations, or if you just hate pictures or something.

Should resolve #119

### CODE REVIEW

**Comment by magnus-ISU** [comment]
I'm not immediately figuring out how preferences are being handled in this app so if someone else wants to do it that would be swell.

**Comment by magnus-ISU** [comment]
Okay, I got the setting toggle working. This is ready to be merged and resolve #119

**Comment by magnus-ISU** [comment]
As a comment, I had to change code in 11 different places to add a new preference. The ideal would be 3 or 4. If there's ever a refactoring effort that should be looked at as a potential improvement.

**Comment by Iamlooker** [comment]
Thanks this is good to go, can you just add 8dp padding to the top of screenshots?

**Comment by vdbhb59** [comment]
Does this actually resolve or handle https://github.com/Droid-ify/client/issues/380 & https://github.com/Droid-ify/client/issues/119 as well?
Else, I will try to check & work on this one (if my limited knowledge allows me to).

**Pull request closed without merging**
