### PR TITLE
Add support for cleartext traffic and self-signed certificates

### PR DESCRIPTION
**Pull request by niks255**

### CODE REVIEW

**Comment by Iamlooker** [comment]
Thanks for the contribution but please make sure you are commiting to `dev` branch.

I will merge this PR and will try to add this to README.md 😄

**Comment by niks255** [comment]
> Thanks for the contribution but please make sure you are commiting to `dev` branch.
> 
> I will merge this PR and will try to add this to README.md 😄

Oops, sorry

**Comment by Bugaddr** [comment]
Cant this be optional ?

**Comment by niks255** [comment]
> Cant this be optional ?

What is the problem with it not being optional?

**Comment by Bugaddr** [comment]
> > Cant this be optional ?
> 
> What is the problem with it not being optional? 
> Cleartext traffic is enabled in the official client as well.

Oh, ok i was unaware of that.

**Pull request merged**
