### PR TITLE
Weblate mentioned in README

### PR DESCRIPTION
**Pull request by comradekingu**
Please delete the project on Crowdin and set up https://docs.weblate.org/en/latest/admin/continuous.html?highlight=webhooks#automatically-receiving-changes-from-github :)

### CODE REVIEW

**Comment by Iamlooker** [comment]
I appreciate your work.

But why would you remove Short and Long Descriptions?

**Comment by comradekingu** [comment]
More descriptive, and it doesn't say "material" three times.

**Comment by Iamlooker** [comment]
Also Weblate Repo link is https://hosted.weblate.org/git/droidify/localization/

**Comment by Iamlooker** [comment]
I would still prefer old description and alignments

> 
> 
> More descriptive, and it doesn't say "material" three times. The correct way to do short and long descriptions is with a fastlane setup I should think (and that can be added to Weblate too).

**Comment by Iamlooker** [comment]
Nope I like you readme but this is not a package manager its a "F-Droid Client"

**Comment by comradekingu** [comment]
@Iamlooker OK. I'll translate it when I find the time :)

**Comment by Iamlooker** [comment]
Thanks for the pull request

**Pull request merged**
